<a href="https://colab.research.google.com/github/celamyrrha/analise_de_dados_CECIERJ/blob/main/Atividade_Semana07_Marcela_Myrrha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade - Semana 07 - Trabalhando com dados

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Importe a planilha `dados_starwars.xlsx` na pasta virtual `content`.

In [ ]:
# Questao 1
import pandas as pd

dados_starwars = pd.read_excel("/content/dados_starwars.xlsx")
dados_starwars

,nome,altura,massa,cor_do_cabelo,cor_da_pele,genero,planeta_natal,especie
0,Luke Skywalker,172.0,77.0,Loiro,Branca clara,Masculino,Tatooine,Humano
1,C-3PO,167.0,75.0,NaN,Ouro,Masculino,Tatooine,Droide
2,R2-D2,96.0,32.0,NaN,"Branca, Azul",Masculino,Naboo,Droide
3,Darth Vader,202.0,136.0,Nenhum,Branca,Masculino,Tatooine,Humano
4,Leia Organa,150.0,49.0,Castanho,Clara,Feminino,Alderaan,Humano
...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,Castanho,Clara,Feminino,NaN,Humano
83,Poe Dameron,NaN,NaN,Castanho,Clara,Masculino,NaN,Humano
84,BB8,NaN,NaN,Nenhum,Nenhuma,Masculino,NaN,Droide
85,Captain Phasma,NaN,NaN,Desconhecido,Desconhecida,NaN,NaN,NaN
86,PadmÃ© Amidala,165.0,45.0,Castanho,Clara,Feminino,Naboo,Humano

###Questão 2

Remova todos os valores faltantes. Salve a base de dados atualizada.

In [ ]:
# Questao 2
dados_starwars = dados_starwars.dropna()
dados_starwars

,nome,altura,massa,cor_do_cabelo,cor_da_pele,genero,planeta_natal,especie
0,Luke Skywalker,172.0,77.0,Loiro,Branca clara,Masculino,Tatooine,Humano
3,Darth Vader,202.0,136.0,Nenhum,Branca,Masculino,Tatooine,Humano
4,Leia Organa,150.0,49.0,Castanho,Clara,Feminino,Alderaan,Humano
5,Owen Lars,178.0,120.0,"Castanho, Cinza",Clara,Masculino,Tatooine,Humano
6,Beru Whitesun lars,165.0,75.0,Castanho,Clara,Feminino,Tatooine,Humano
8,Biggs Darklighter,183.0,84.0,Preto,Clara,Masculino,Tatooine,Humano
9,Obi-Wan Kenobi,182.0,77.0,"Ruivo, Branco",Branca clara,Masculino,Stewjon,Humano
10,Anakin Skywalker,188.0,84.0,Loiro,Branca clara,Masculino,Tatooine,Humano
12,Chewbacca,228.0,112.0,Castanho,Desconhecida,Masculino,Kashyyyk,Wookiee
13,Han Solo,180.0,80.0,Castanho,Branca clara,Masculino,Corellia,Humano
16,Wedge Antilles,170.0,77.0,Castanho,Branca clara,Masculino,Corellia,Humano
17,Jek Tono Porkins,180.0,110.0,Castanho,Branca clara,Masculino,Bestine IV,Humano
19,Palpatine,170.0,75.0,Cinza,"B""ranca p\u00e1lida",Masculino,Naboo,Humano
20,Boba Fett,183.0,78.2,Preto,Branca clara,Masculino,Kamino,Humano
22,Bossk,190.0,113.0,Nenhum,Verde,Masculino,Trandosha,Trandoshano
23,Lando Calrissian,177.0,79.0,Preto,Negra,Masculino,Socorro,Humano
24,Lobot,175.0,79.0,Nenhum,Clara,Masculino,Bespin,Humano
25,Ackbar,180.0,83.0,Nenhum,Marrom com manchas,Masculino,Mon Cala,Mon Calamari
28,Wicket Systri Warrick,88.0,20.0,Castanho,Marrom,Masculino,Endor,Ewok
29,Nien Nunb,160.0,68.0,Nenhum,Cinza,Masculino,Sullust,Sullustano
31,Nute Gunray,191.0,90.0,Nenhum,Verde com manchas,Masculino,Cato Neimoidia,Neimoidiano
33,Jar Jar Binks,196.0,66.0,Nenhum,Larajna,Masculino,Naboo,Gungan
34,Roos Tarpals,224.0,82.0,Nenhum,Cinza,Masculino,Naboo,Gungan
38,Sebulba,112.0,40.0,Nenhum,"Cinza, Vermelha",Masculino,Malastare,Dug
41,Darth Maul,175.0,80.0,Nenhum,Vermelha,Masculino,Dathomir,Zabrak
43,Ayla Secura,178.0,55.0,Nenhum,Azul,Feminino,Ryloth,Twi'lek
44,Dud Bolt,94.0,45.0,Nenhum,"Azul, Cinza",Masculino,Vulpter,Vulptereen
46,Ben Quadinaros,163.0,65.0,Nenhum,"Cinza, Verde, Amarela",Masculino,Tund,Toong
47,Mace Windu,188.0,84.0,Nenhum,Negra,Masculino,Haruun Kal,Humano
48,Ki-Adi-Mundi,198.0,82.0,Branco,"B""ranca p\u00e1lida",Masculino,Cerea,Cerean
49,Kit Fisto,196.0,87.0,Nenhum,Verde,Masculino,Glee Anselm,Nautolan
51,Adi Gallia,184.0,50.0,Nenhum,Negra,Feminino,Coruscant,Tholotiano
54,Plo Koon,188.0,80.0,Nenhum,Larajna,Masculino,Dorin,Kel Dor
56,Gregar Typho,185.0,85.0,Preto,Negra,Masculino,Naboo,Humano
59,Poggle the Lesser,183.0,80.0,Nenhum,Verde,Masculino,Geonosis,Geonosiano
60,Luminara Unduli,170.0,56.2,Preto,Amarela,Feminino,Mirial,Mirialan
61,Barriss Offee,166.0,50.0,Preto,Amarela,Feminino,Mirial,Mirialan
63,Dooku,193.0,80.0,Branco,Branca clara,Masculino,Serenno,Humano
65,Jango Fett,183.0,79.0,Preto,Bronzeada,Masculino,Concord Dawn,Humano
66,Zam Wesell,168.0,55.0,Loiro,"Branca clara, Verde, Amarela",Feminino,Zolan,Clawdite
67,Dexter Jettster,198.0,102.0,Nenhum,Marrom,Masculino,Ojom,Besalisk
68,Lama Su,229.0,88.0,Nenhum,Cinza,Masculino,Kamino,Kaminoan
71,Ratts Tyerell,79.0,15.0,Nenhum,"Cinza, Azul",Masculino,Aleen Minor,Aleena
73,Wat Tambor,193.0,48.0,Nenhum,"Verde, Cinza",Masculino,Skako,Skakoano
75,Shaak Ti,178.0,57.0,Nenhum,"Vermelha, Azul, Branca",Feminino,Shili,Togruta
76,Grievous,216.0,159.0,Nenhum,"Marrom, Branca",Masculino,Kalee,Kaleesh
77,Tarfful,234.0,136.0,Castanho,Marrom,Masculino,Kashyyyk,Wookiee
78,Raymus Antilles,188.0,79.0,Castanho,Clara,Masculino,Alderaan,Humano
80,Tion Medon,206.0,80.0,Nenhum,Cinza,Masculino,Utapau,Pau'ano
86,PadmÃ© Amidala,165.0,45.0,Castanho,Clara,Feminino,Naboo,Humano

###Questão 3

Filtre somente os registros com `especie` = `humano`. Salve a base de dados atualizada.

In [ ]:
# Questao 3
dados_starwars = dados_starwars[dados_starwars["especie"] == "Humano"]
dados_starwars

,nome,altura,massa,cor_do_cabelo,cor_da_pele,genero,planeta_natal,especie
0,Luke Skywalker,172.0,77.0,Loiro,Branca clara,Masculino,Tatooine,Humano
3,Darth Vader,202.0,136.0,Nenhum,Branca,Masculino,Tatooine,Humano
4,Leia Organa,150.0,49.0,Castanho,Clara,Feminino,Alderaan,Humano
5,Owen Lars,178.0,120.0,"Castanho, Cinza",Clara,Masculino,Tatooine,Humano
6,Beru Whitesun lars,165.0,75.0,Castanho,Clara,Feminino,Tatooine,Humano
8,Biggs Darklighter,183.0,84.0,Preto,Clara,Masculino,Tatooine,Humano
9,Obi-Wan Kenobi,182.0,77.0,"Ruivo, Branco",Branca clara,Masculino,Stewjon,Humano
10,Anakin Skywalker,188.0,84.0,Loiro,Branca clara,Masculino,Tatooine,Humano
13,Han Solo,180.0,80.0,Castanho,Branca clara,Masculino,Corellia,Humano
16,Wedge Antilles,170.0,77.0,Castanho,Branca clara,Masculino,Corellia,Humano
17,Jek Tono Porkins,180.0,110.0,Castanho,Branca clara,Masculino,Bestine IV,Humano
19,Palpatine,170.0,75.0,Cinza,"B""ranca p\u00e1lida",Masculino,Naboo,Humano
20,Boba Fett,183.0,78.2,Preto,Branca clara,Masculino,Kamino,Humano
23,Lando Calrissian,177.0,79.0,Preto,Negra,Masculino,Socorro,Humano
24,Lobot,175.0,79.0,Nenhum,Clara,Masculino,Bespin,Humano
47,Mace Windu,188.0,84.0,Nenhum,Negra,Masculino,Haruun Kal,Humano
56,Gregar Typho,185.0,85.0,Preto,Negra,Masculino,Naboo,Humano
63,Dooku,193.0,80.0,Branco,Branca clara,Masculino,Serenno,Humano
65,Jango Fett,183.0,79.0,Preto,Bronzeada,Masculino,Concord Dawn,Humano
78,Raymus Antilles,188.0,79.0,Castanho,Clara,Masculino,Alderaan,Humano
86,PadmÃ© Amidala,165.0,45.0,Castanho,Clara,Feminino,Naboo,Humano

###Questão 4

Edite a variável `altura` (que esta em centímetros) para que passe para a unidade em metros (*dividir por 100*). Salve a base de dados atualizada.

In [ ]:
# Questao 4
dados_starwars["altura"] = dados_starwars["altura"] / 100
dados_starwars

<ipython-input-13-cac80d3cbd34>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_starwars["altura"] = dados_starwars["altura"] / 100

,nome,altura,massa,cor_do_cabelo,cor_da_pele,genero,planeta_natal,especie
0,Luke Skywalker,1.72,77.0,Loiro,Branca clara,Masculino,Tatooine,Humano
3,Darth Vader,2.02,136.0,Nenhum,Branca,Masculino,Tatooine,Humano
4,Leia Organa,1.50,49.0,Castanho,Clara,Feminino,Alderaan,Humano
5,Owen Lars,1.78,120.0,"Castanho, Cinza",Clara,Masculino,Tatooine,Humano
6,Beru Whitesun lars,1.65,75.0,Castanho,Clara,Feminino,Tatooine,Humano
8,Biggs Darklighter,1.83,84.0,Preto,Clara,Masculino,Tatooine,Humano
9,Obi-Wan Kenobi,1.82,77.0,"Ruivo, Branco",Branca clara,Masculino,Stewjon,Humano
10,Anakin Skywalker,1.88,84.0,Loiro,Branca clara,Masculino,Tatooine,Humano
13,Han Solo,1.80,80.0,Castanho,Branca clara,Masculino,Corellia,Humano
16,Wedge Antilles,1.70,77.0,Castanho,Branca clara,Masculino,Corellia,Humano
17,Jek Tono Porkins,1.80,110.0,Castanho,Branca clara,Masculino,Bestine IV,Humano
19,Palpatine,1.70,75.0,Cinza,"B""ranca p\u00e1lida",Masculino,Naboo,Humano
20,Boba Fett,1.83,78.2,Preto,Branca clara,Masculino,Kamino,Humano
23,Lando Calrissian,1.77,79.0,Preto,Negra,Masculino,Socorro,Humano
24,Lobot,1.75,79.0,Nenhum,Clara,Masculino,Bespin,Humano
47,Mace Windu,1.88,84.0,Nenhum,Negra,Masculino,Haruun Kal,Humano
56,Gregar Typho,1.85,85.0,Preto,Negra,Masculino,Naboo,Humano
63,Dooku,1.93,80.0,Branco,Branca clara,Masculino,Serenno,Humano
65,Jango Fett,1.83,79.0,Preto,Bronzeada,Masculino,Concord Dawn,Humano
78,Raymus Antilles,1.88,79.0,Castanho,Clara,Masculino,Alderaan,Humano
86,PadmÃ© Amidala,1.65,45.0,Castanho,Clara,Feminino,Naboo,Humano

###Questão 5

Renomeie a variável `altura` para `altura_metros`. Salve a base de dados atualizada.

In [ ]:
# Questao 5
dados_starwars = dados_starwars.rename(columns={"altura":"altura_metros"})
dados_starwars

,nome,altura_metros,massa,cor_do_cabelo,cor_da_pele,genero,planeta_natal,especie
0,Luke Skywalker,1.72,77.0,Loiro,Branca clara,Masculino,Tatooine,Humano
3,Darth Vader,2.02,136.0,Nenhum,Branca,Masculino,Tatooine,Humano
4,Leia Organa,1.50,49.0,Castanho,Clara,Feminino,Alderaan,Humano
5,Owen Lars,1.78,120.0,"Castanho, Cinza",Clara,Masculino,Tatooine,Humano
6,Beru Whitesun lars,1.65,75.0,Castanho,Clara,Feminino,Tatooine,Humano
8,Biggs Darklighter,1.83,84.0,Preto,Clara,Masculino,Tatooine,Humano
9,Obi-Wan Kenobi,1.82,77.0,"Ruivo, Branco",Branca clara,Masculino,Stewjon,Humano
10,Anakin Skywalker,1.88,84.0,Loiro,Branca clara,Masculino,Tatooine,Humano
13,Han Solo,1.80,80.0,Castanho,Branca clara,Masculino,Corellia,Humano
16,Wedge Antilles,1.70,77.0,Castanho,Branca clara,Masculino,Corellia,Humano
17,Jek Tono Porkins,1.80,110.0,Castanho,Branca clara,Masculino,Bestine IV,Humano
19,Palpatine,1.70,75.0,Cinza,"B""ranca p\u00e1lida",Masculino,Naboo,Humano
20,Boba Fett,1.83,78.2,Preto,Branca clara,Masculino,Kamino,Humano
23,Lando Calrissian,1.77,79.0,Preto,Negra,Masculino,Socorro,Humano
24,Lobot,1.75,79.0,Nenhum,Clara,Masculino,Bespin,Humano
47,Mace Windu,1.88,84.0,Nenhum,Negra,Masculino,Haruun Kal,Humano
56,Gregar Typho,1.85,85.0,Preto,Negra,Masculino,Naboo,Humano
63,Dooku,1.93,80.0,Branco,Branca clara,Masculino,Serenno,Humano
65,Jango Fett,1.83,79.0,Preto,Bronzeada,Masculino,Concord Dawn,Humano
78,Raymus Antilles,1.88,79.0,Castanho,Clara,Masculino,Alderaan,Humano
86,PadmÃ© Amidala,1.65,45.0,Castanho,Clara,Feminino,Naboo,Humano

###Questão 6

Ordene a base de dados por `altura_metros`. Salve a base de dados atualizada.

In [ ]:
# Questao 6
dados_starwars = dados_starwars.sort_values(by="altura_metros")
dados_starwars

###Questão 7

Mantenha na base somente as variáveis: `nome`, `altura_metros`, `massa` e `genero`. Salve a base de dados atualizada.

In [ ]:
# Questao 7
dados_starwars = dados_starwars.iloc[:, [0, 1 ,2, 5]]
dados_starwars

                  nome  altura_metros  massa     genero
4          Leia Organa           1.50   49.0   Feminino
86      PadmÃ© Amidala           1.65   45.0   Feminino
6   Beru Whitesun lars           1.65   75.0   Feminino
19           Palpatine           1.70   75.0  Masculino
16      Wedge Antilles           1.70   77.0  Masculino
0       Luke Skywalker           1.72   77.0  Masculino
24               Lobot           1.75   79.0  Masculino
23    Lando Calrissian           1.77   79.0  Masculino
5            Owen Lars           1.78  120.0  Masculino
13            Han Solo           1.80   80.0  Masculino
17    Jek Tono Porkins           1.80  110.0  Masculino
9       Obi-Wan Kenobi           1.82   77.0  Masculino
20           Boba Fett           1.83   78.2  Masculino
65          Jango Fett           1.83   79.0  Masculino
8    Biggs Darklighter           1.83   84.0  Masculino
56        Gregar Typho           1.85   85.0  Masculino
10    Anakin Skywalker           1.88   84.0  Masculino
78     Raymus Antilles           1.88   79.0  Masculino
47          Mace Windu           1.88   84.0  Masculino
63               Dooku           1.93   80.0  Masculino
3          Darth Vader           2.02  136.0  Masculino